// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOsrW2jhu36Wu28TniTjngZPlfDIO2ZkI',
    appId: '1:754160068044:web:db6236d05489bcc6512969',
    messagingSenderId: '754160068044',
    projectId: 'dukan-959a2',
    authDomain: 'dukan-959a2.firebaseapp.com',
    databaseURL: 'https://dukan-959a2-default-rtdb.firebaseio.com',
    storageBucket: 'dukan-959a2.appspot.com',
    measurementId: 'G-1J8XPKVKX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU6l-vCVsqnQa1qj-qlSvAk6e0JRw2aAg',
    appId: '1:754160068044:android:b33f612108dfa7a4512969',
    messagingSenderId: '754160068044',
    projectId: 'dukan-959a2',
    databaseURL: 'https://dukan-959a2-default-rtdb.firebaseio.com',
    storageBucket: 'dukan-959a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbL5u-H9ZyDW9QiJc7Qtm2VcZGVLH-t0A',
    appId: '1:754160068044:ios:7ec3bc5a3e407022512969',
    messagingSenderId: '754160068044',
    projectId: 'dukan-959a2',
    databaseURL: 'https://dukan-959a2-default-rtdb.firebaseio.com',
    storageBucket: 'dukan-959a2.appspot.com',
    iosBundleId: 'com.example.dukan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbL5u-H9ZyDW9QiJc7Qtm2VcZGVLH-t0A',
    appId: '1:754160068044:ios:7ec3bc5a3e407022512969',
    messagingSenderId: '754160068044',
    projectId: 'dukan-959a2',
    databaseURL: 'https://dukan-959a2-default-rtdb.firebaseio.com',
    storageBucket: 'dukan-959a2.appspot.com',
    iosBundleId: 'com.example.dukan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOsrW2jhu36Wu28TniTjngZPlfDIO2ZkI',
    appId: '1:754160068044:web:7848fdec12ba6251512969',
    messagingSenderId: '754160068044',
    projectId: 'dukan-959a2',
    authDomain: 'dukan-959a2.firebaseapp.com',
    databaseURL: 'https://dukan-959a2-default-rtdb.firebaseio.com',
    storageBucket: 'dukan-959a2.appspot.com',
    measurementId: 'G-6K4RXG2PW0',
  );
}
